[package]
name = "subspace-core-primitives"
description = "Core primitives for Subspace Network"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
include = [
    "/src",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md"
]

[dependencies]
parity-scale-codec = { version = "2.3.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
sha2 = { version = "0.9.8", default-features = false }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "scale-info/std",
    "serde/std",
    # Can't enable this in platform-specific way, see https://github.com/rust-lang/cargo/issues/1197
    #"sha2/asm",
    "sha2/std",
]
