[package]
name = "subspace-solving"
description = "Encoder for the Subspace Network Blockchain based on the SLOTH permutation"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }

[features]
default = [
    "std",
]
std = [
    "subspace-core-primitives/std",
]
