[package]
name = "subspace-verification"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Verification primitives for Subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
schnorrkel = { version = "0.9.1", default-features = false, features = ["u64_backend"] }
sp-arithmetic = { version = "16.0.0", default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "920fb277d5ea16a3b0918052c7555026a1ac2c6c" }
sp-std = { version = "8.0.0", default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "920fb277d5ea16a3b0918052c7555026a1ac2c6c" }
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving", default-features = false }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }
subspace-proof-of-space = { version = "0.1.0", path = "../subspace-proof-of-space", default-features = false }
thiserror = { version = "1.0.48", optional = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "schnorrkel/std",
    "sp-arithmetic/std",
    "sp-std/std",
    "subspace-archiving/std",
    "subspace-core-primitives/std",
    "thiserror"
]
