[workspace]
members = [
    "bin/node-template-spartan/node",
    "bin/node-template-spartan/runtime",
    "crates/sc-consensus-poc",
    "crates/sc-consensus-poc-rpc",
    "crates/pallet-offences-poc",
    "crates/pallet-spartan",
    "crates/sp-consensus-poc",
    "crates/sp-consensus-spartan",
]
