[workspace]
resolver = "2"
members = [
    "crates/*",
    "cumulus/client/block-builder",
    "cumulus/client/cli",
    "cumulus/client/cirrus-service",
    "cumulus/client/cirrus-executor",
    "cumulus/client/consensus/common",
    "cumulus/client/consensus/relay-chain",
    "cumulus/client/executor-gossip",
    "cumulus/pallets/executive",
    "cumulus/parachain-template/node",
    "cumulus/parachain-template/runtime",
    "cumulus/primitives",
    "polkadot/node/collation-generation",
    "polkadot/node/core/chain-api",
    "polkadot/node/core/runtime-api",
    "polkadot/node/jaeger",
    "polkadot/node/metered-channel",
    "polkadot/node/metrics",
    "polkadot/node/overseer",
    "polkadot/node/overseer/overseer-gen",
    "polkadot/node/overseer/overseer-gen/proc-macro",
    "polkadot/node/subsystem",
    "polkadot/node/subsystem-types",
    "polkadot/node/subsystem-util",
    "substrate/*",
]

[patch."https://github.com/paritytech/substrate"]
sc-block-builder = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-chain-spec = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-cli = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-client-api = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-client-db = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-consensus = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-consensus-slots = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-consensus-uncles = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-executor = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-informant = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-keystore = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-network = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-network-gossip = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-offchain = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-rpc = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-rpc-api = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-service = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-telemetry = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-tracing = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-transaction-pool = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sc-transaction-pool-api = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }

sp-api = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-application-crypto = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-arithmetic = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-block-builder = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-blockchain = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-consensus = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-consensus-slots = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-core = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-externalities = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-inherents = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-io = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-keystore = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-keyring = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-offchain = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-rpc = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-runtime = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-runtime-interface = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-session = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-state-machine = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-std = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-storage = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-timestamp = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-tracing = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-transaction-pool = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-trie = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
sp-version = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }

frame-benchmarking-cli = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
frame-executive = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
frame-support = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
frame-system = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
frame-system-rpc-runtime-api = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }

substrate-frame-rpc-system = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }

pallet-balances = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-session = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-sudo = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-timestamp = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-transaction-payment = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-transaction-payment-rpc = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }
pallet-utility = { git = "https://github.com/subspace/substrate", branch = "cirrus-executive" }

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# This list is ordered alphabetically.
[profile.dev.package]
blake2 = { opt-level = 3 }
blake2-rfc = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
reed-solomon-erasure = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
sloth256-189 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
subspace-core-primitives = { opt-level = 3 }
subspace-archiving = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
