[package]
name = "system-domain-runtime"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Runtime, ready for hacking together a parachain."
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/cumulus/"
edition = "2021"
links = "system-domain-runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"]}
core-payments-domain-runtime = { path = "../../runtime/core-payments", default-features = false }
domain-pallet-executive = { path = "../../pallets/executive", default-features = false }
domain-runtime-primitives = { path = "../../primitives/runtime", default-features = false }
frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
frame-support = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
frame-system = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
frame-system-benchmarking = { default-features = false, optional = true, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
pallet-balances = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
pallet-domain-registry = { path = "../../pallets/domain-registry", default-features = false }
pallet-domain-tracker = { path = "../../pallets/domain-tracker", default-features = false }
pallet-executor-registry = { path = "../../pallets/executor-registry", default-features = false }
pallet-messenger = { path = "../../pallets/messenger", default-features = false }
pallet-transaction-payment = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
pallet-transporter = { path = "../../pallets/transporter", default-features = false }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }
sp-api = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-block-builder = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-core = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-domain-tracker = { path = "../../primitives/domain-tracker", default-features = false }
sp-domains = { path = "../../../crates/sp-domains", default-features = false }
sp-inherents = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-io = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-messenger = { path = "../../primitives/messenger", default-features = false }
sp-offchain = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-runtime = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-session = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-std = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-transaction-pool = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
sp-version = { default-features = false, git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }
subspace-runtime-primitives = { path = "../../../crates/subspace-runtime-primitives", default-features = false }
system-runtime-primitives = { path = "../../primitives/system-runtime", default-features = false }

[build-dependencies]
subspace-wasm-tools = { version = "0.1.0", default-features = false, path = "../../../crates/subspace-wasm-tools" }
substrate-wasm-builder = { git = "https://github.com/subspace/substrate", rev = "6d57dbc639bb3d9460dabeccb063cc6556452535" }

[features]
default = [
	"std",
]
std = [
	"codec/std",
	"core-payments-domain-runtime/std",
	"domain-pallet-executive/std",
	"domain-runtime-primitives/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-balances/std",
	"pallet-domain-registry/std",
	"pallet-domain-tracker/std",
	"pallet-executor-registry/std",
	"pallet-messenger/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transporter/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-domain-tracker/std",
	"sp-domains/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-messenger/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"subspace-runtime-primitives/std",
	"system-runtime-primitives/std",
]
# Internal implementation detail, enabled during building of wasm blob.
wasm-builder = []
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
