[package]
name = "sp-messenger"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Primitives for Messenger"
include = [
	"/src",
	"/Cargo.toml",
	"/README.md",
]

[dependencies]


[features]
default = ["std"]
std = []
