[package]
name = "polkadot-node-metrics"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Subsystem traits and message definitions"

[dependencies]
futures = "0.3.17"
futures-timer = "3.0.2"

metered-channel = { path = "../metered-channel" }

substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }

[features]
default = []
