[package]
name = "sp-lightclient"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Light client substrate primitives for Subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
sp-arithmetic = { version = "5.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "sp-arithmetic/std",
    "subspace-core-primitives/std"
]
