[package]
name = "sp-lightclient"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Light client substrate primitives for Subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false }
scale-info = { version = "2.11.2", default-features = false, features = ["derive"] }
schnorrkel = { version = "0.11.4", default-features = false }
sp-arithmetic = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "808269708cf5375526755797e8f9a9986016727d" }
sp-consensus-slots = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "808269708cf5375526755797e8f9a9986016727d" }
sp-consensus-subspace = { version = "0.1.0", path = "../sp-consensus-subspace", default-features = false }
sp-runtime = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "808269708cf5375526755797e8f9a9986016727d" }
sp-std = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "808269708cf5375526755797e8f9a9986016727d" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }
subspace-erasure-coding = { version = "0.1.0", path = "../subspace-erasure-coding", default-features = false }
subspace-verification = { version = "0.1.0", path = "../subspace-verification", default-features = false }

[dev-dependencies]
frame-support = { git = "https://github.com/subspace/polkadot-sdk", rev = "808269708cf5375526755797e8f9a9986016727d" }
futures = "0.3.29"
rand = { version = "0.8.5", features = ["min_const_gen"] }
sp-io = { git = "https://github.com/subspace/polkadot-sdk", rev = "808269708cf5375526755797e8f9a9986016727d" }
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-farmer-components = { version = "0.1.0", path = "../subspace-farmer-components" }
subspace-proof-of-space = { version = "0.1.0", path = "../subspace-proof-of-space" }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "schnorrkel/std",
    "sp-arithmetic/std",
    "sp-consensus-slots/std",
    "sp-consensus-subspace/std",
    "sp-runtime/std",
    "sp-std/std",
    "subspace-core-primitives/std",
    "subspace-verification/std"
]
