[package]
name = "subspace-archiving"
description = "Collection of modules used for dealing with archived state of Subspace Network"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
merkletree = "0.21.0"
parity-scale-codec = { version = "2.3.0", features = ["derive"], default-features = false }
reed-solomon-erasure = { version = "5.0.0", default-features = true }
serde = { version = "1.0.130", optional = true, features = ["derive"] }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }
thiserror = "1.0.29"
typenum = "1.14.0"

# Ugly workaround for https://github.com/rust-lang/cargo/issues/1197
[target.'cfg(any(target_os = "linux", target_os = "macos", all(target_os = "windows", target_env = "gnu")))'.dependencies.sha2]
features = ["asm"]
version = "0.9.8"

# Ugly workaround for https://github.com/rust-lang/cargo/issues/1197
# `asm` feature is not supported on Windows except with GNU toolchain
[target.'cfg(not(any(target_os = "linux", target_os = "macos", all(target_os = "windows", target_env = "gnu"))))'.dependencies.sha2]
default-features = false
version = "0.9.8"

[dev-dependencies]
rand = { version = "0.8.4", features = ["min_const_gen"] }

# TODO: Nothing is exposed in no-std environment at the moment :(
[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "reed-solomon-erasure/simd-accel",
    "serde",
    "sha2/std",
    "subspace-core-primitives/std",
]
