[package]
name = "subspace-archiving"
description = "Collection of modules used for dealing with archived state of Subspace Network"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
include = [
    "/src",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md"
]

[dependencies]
merkletree = "0.21.0"
parity-scale-codec = { version = "2.3.0", features = ["derive"], default-features = false }
rand = { version = "0.8.4", features = ["min_const_gen"] }
reed-solomon-erasure = { version = "4.0.2", features = ["simd-accel"] }
sha2 = { version = "0.9.8", default-features = false }
thiserror = "1.0.29"
typenum = "1.14.0"

subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }

# TODO: Nothing is exposed in no-std environment at the moment :(
[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    # Can't enable this in platform-specific way, see https://github.com/rust-lang/cargo/issues/1197
    "sha2/asm",
    "sha2/std",
    "subspace-core-primitives/std",
]
