[package]
name = "pallet-operator-rewards"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Subspace node pallet for charging and re-distributing domain transaction fees"
include = [
  "/src",
  "/Cargo.toml",
]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
domain-runtime-primitives = { version = "0.1.0", path = "../../primitives/runtime", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "0831dfc3c54b10ab46e82acf98603b4af1a47bd5" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "0831dfc3c54b10ab46e82acf98603b4af1a47bd5" }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
sp-operator-rewards = { version = "0.1.0", path = "../../primitives/operator-rewards", default-features = false }
sp-runtime = { version = "24.0.0", default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "0831dfc3c54b10ab46e82acf98603b4af1a47bd5" }
sp-std = { version = "8.0.0", default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "0831dfc3c54b10ab46e82acf98603b4af1a47bd5" }

[features]
default = ["std"]
std = [
  "codec/std",
  "domain-runtime-primitives/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "sp-operator-rewards/std",
  "sp-runtime/std",
  "sp-std/std",
]
