[package]
name = "subspace-proof-of-space"
description = "Subspace proof of space implementation based on Chia"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/benches",
    "/src",
    "/Cargo.toml",
]

[dependencies]
subspace-chiapos = { git = "https://github.com/subspace/chiapos", rev = "100f861378c3f450434ef9e94723f50c804d333f" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "pos"
harness = false
