[target.'cfg(target_arch = "x86_64")']
# Require AES-NI on x86-64 by default
rustflags = ["-C", "target-feature=+aes"]

[target.'cfg(target_arch = "aarch64")']
# TODO: AES flag is such that we have decent performance on ARMv8, remove once `aes` crate bumps MSRV to at least
#  1.61: https://github.com/RustCrypto/block-ciphers/issues/373
rustflags = ["--cfg", "aes_armv8"]
