[package]
name = "polkadot-overseer"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
client = { package = "sc-client-api", git = "https://github.com/paritytech/substrate", rev = "04c7c6abef1e0c6b4126427159090a44f3221333" }
sp-api = { git = "https://github.com/paritytech/substrate", rev = "04c7c6abef1e0c6b4126427159090a44f3221333" }
futures = "0.3.19"
futures-timer = "3.0.2"
parking_lot = "0.11.2"
polkadot-node-subsystem-types = { path = "../subsystem-types" }
polkadot-node-metrics = { path = "../metrics" }
polkadot-overseer-gen = { path = "./overseer-gen" }
tracing = "0.1.29"
lru = "0.7"
parity-util-mem = { version = ">= 0.10.1", default-features = false }

cirrus-node-primitives = { path = "../../../crates/cirrus-node-primitives" }
subspace-runtime-primitives = { path = "../../../crates/subspace-runtime-primitives" }

[dev-dependencies]
metered-channel = { path = "../metered-channel" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "04c7c6abef1e0c6b4126427159090a44f3221333" }
futures = { version = "0.3.19", features = ["thread-pool"] }

[features]
default = []
