[package]
name = "polkadot-overseer"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.52"
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-api = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
futures = "0.3.21"
futures-timer = "3.0.2"
parking_lot = "0.12.0"
smallvec = "1.8.0"
thiserror = "1.0.30"
tracing = "0.1.32"
lru = "0.7.3"
metered = { package = "metered-channel", path = "../metered-channel" }
pin-project = "1.0.10"

cirrus-node-primitives = { path = "../../../crates/cirrus-node-primitives" }
sp-executor = { path = "../../../crates/sp-executor" }
subspace-runtime-primitives = { path = "../../../crates/subspace-runtime-primitives" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }

[features]
default = []
