[package]
name = "subspace-farmer"
description = "Farmer for the Subspace Network Blockchain"
license = "MIT OR Apache-2.0"
version = "0.3.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
anyhow = "1.0.44"
async-oneshot = "0.5.0"
async-trait = "0.1.52"
clap = { version = "3.0.0-rc.7", features = ["color", "derive"] }
dirs = "4.0.0"
env_logger = "0.9.0"
event-listener-primitives = "2.0.1"
futures = "0.3.17"
hex = "0.4.3"
hex-buffer-serde = "0.3.0"
jsonrpsee = { version = "0.6.1", features = ["client", "macros", "server"] }
log = "0.4.14"
lru = "0.7.0"
parity-scale-codec = "2.3.0"
parking_lot = "0.11.2"
rayon = "1.5.1"
schnorrkel = "0.9.1"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.73"
sp-core = { version = "4.1.0-dev", git = "https://github.com/paritytech/substrate", rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
ss58-registry = "1.10.0"
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving" }
subspace-solving = { version = "0.1.0", path = "../subspace-solving" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-rpc-primitives = { version = "0.1.0", path = "../subspace-rpc-primitives" }
thiserror = "1.0.24"
tiny-bip39 = "0.8.2"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }

[dependencies.rocksdb]
# This disables compression algorithms that cause issues during linking due to
# https://github.com/rust-rocksdb/rust-rocksdb/issues/514
default-features = false
# `zstd` causes compilation errors, others are unnecessary for now
features = ["snappy"]
version = "0.17.0"

[dev-dependencies]
rand = "0.8.4"
tempfile = "3.2.0"

[features]
default = []
# Compile with CUDA support and use it if compatible GPU is available
cuda = [
    "subspace-solving/cuda",
]
