[package]
name = "subspace-farmer"
description = "Farmer for the Subspace Network Blockchain"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
anyhow = "1.0.86"
async-lock = "3.3.0"
async-nats = "0.35.1"
async-trait = "0.1.81"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
base58 = "0.2.0"
blake2 = "0.10.6"
blake3 = { version = "1.5.3", default-features = false }
bytes = "1.7.1"
bytesize = "1.3.0"
clap = { version = "4.5.15", features = ["color", "derive"] }
criterion = { version = "0.5.1", default-features = false, features = ["rayon", "async"] }
derive_more = { version = "1.0.0", features = ["full"] }
event-listener = "5.3.1"
event-listener-primitives = "2.0.1"
fdlimit = "0.3.0"
fs4 = "0.8.4"
futures = "0.3.29"
hex = { version = "0.4.3", features = ["serde"] }
hwlocality = { version = "1.0.0-alpha.6", features = ["vendored"], optional = true }
jsonrpsee = { version = "0.24.2", features = ["ws-client"] }
mimalloc = "0.1.43"
num_cpus = "1.16.0"
parity-scale-codec = "3.6.12"
parking_lot = "0.12.2"
pin-project = "1.1.5"
prometheus-client = "0.22.3"
rand = "0.8.5"
rayon = "1.10.0"
schnellru = "0.2.3"
schnorrkel = "0.11.4"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
static_assertions = "1.1.0"
ss58-registry = "1.47.0"
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving" }
subspace-erasure-coding = { version = "0.1.0", path = "../subspace-erasure-coding" }
subspace-farmer-components = { version = "0.1.0", path = "../subspace-farmer-components" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-metrics = { version = "0.1.0", path = "../../shared/subspace-metrics" }
subspace-networking = { version = "0.1.0", path = "../subspace-networking" }
subspace-proof-of-space = { version = "0.1.0", path = "../subspace-proof-of-space" }
subspace-rpc-primitives = { version = "0.1.0", path = "../subspace-rpc-primitives" }
substrate-bip39 = "0.6.0"
supports-color = "3.0.0"
tempfile = "3.12.0"
thiserror = "1.0.63"
thread-priority = "1.1.0"
tokio = { version = "1.39.2", features = ["macros", "parking_lot", "rt-multi-thread", "signal", "time"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ulid = { version = "1.1.3", features = ["serde"] }
zeroize = "1.8.1"

[features]
default = ["numa"]
numa = ["dep:hwlocality"]
