[package]
name = "subspace-node"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
description = "A Subspace Network Blockchain node."
edition = "2021"
license = "GPL-3.0-or-later"
build = "build.rs"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
	"/res",
	"/src",
	"/build.rs",
	"/Cargo.toml",
	"/README.md"
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
cirrus-node = { version = "0.1.0", path = "../../cumulus/node" }
cirrus-runtime = { version = "0.1.0", path = "../../cumulus/runtime" }
clap = { version = "3.1.18", features = ["derive"] }
dirs = "4.0.0"
frame-benchmarking-cli = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
futures = "0.3.21"
log = "0.4.17"
parity-scale-codec = "3.1.2"
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
sc-cli = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831", features = ["wasmtime"] }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831", features = ["wasmtime"] }
sc-service = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831", features = ["wasmtime"] }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
sc-tracing = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
serde = "1.0.136"
serde_json = "1.0.79"
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
sp-executor = { version = "0.1.0", path = "../sp-executor" }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-networking = { version = "0.1.0", path = "../subspace-networking" }
subspace-runtime = { version = "0.1.0", path = "../subspace-runtime" }
subspace-runtime-primitives = { version = "0.1.0", path = "../subspace-runtime-primitives" }
subspace-service = { version = "0.1.0", path = "../subspace-service" }
thiserror = "1.0.30"
tokio = { version = "1.17.0" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev = "5d3e7c4ee9f5c8e370022d5f3fa9723185710831" }

[features]
default = ["do-not-enforce-cost-of-storage"]
do-not-enforce-cost-of-storage = [
	"subspace-runtime/do-not-enforce-cost-of-storage"
]
runtime-benchmarks = [
	"cirrus-node/runtime-benchmarks",
	"cirrus-runtime/runtime-benchmarks",
	"subspace-runtime/runtime-benchmarks",
]
