[package]
name = "subspace-node"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
description = "A Subspace Network Blockchain node."
edition = "2021"
license = "GPL-3.0-or-later"
build = "build.rs"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
	"/src",
	"/build.rs",
	"/Cargo.toml",
	"/README.md"
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
frame-benchmarking-cli = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927" }
futures = "0.3.19"
sc-cli = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927", features = ["wasmtime"] }
sc-service = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927", features = ["wasmtime"] }
sp-core = { version = "5.0.0", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927" }
subspace-service = { version = "0.1.0", path = "../subspace-service" }
thiserror = "1.0.30"

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927" }

[features]
default = []
runtime-benchmarks = [
	"subspace-service/runtime-benchmarks",
]
json-chain-spec = ["subspace-service/json-chain-spec"]
