[package]
name = "subspace-runtime"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
license = "GPL-3.0-or-later"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
	"/src",
	"/build.rs",
	"/Cargo.toml",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parachain-template-runtime = { version = "0.1.0", default-features = false, path = "../../cumulus/parachain-template/runtime" }
subspace-consensus-runtime = { version = "0.1.0", default-features = false, path = "../subspace-consensus-runtime" }

[build-dependencies]
substrate-wasm-builder = { version = "5.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }

[features]
default = ["std"]
std = [
	"parachain-template-runtime/std",
	"subspace-consensus-runtime/std",
]
runtime-benchmarks = [
	"parachain-template-runtime/runtime-benchmarks",
	"subspace-consensus-runtime/runtime-benchmarks",
]
do-not-enforce-cost-of-storage = [
	"subspace-consensus-runtime/do-not-enforce-cost-of-storage"
]
