[package]
name = "parachain-template-runtime"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Runtime, ready for hacking together a parachain."
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/cumulus/"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }

[dependencies]
hex-literal = { version = '0.3.1', optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
log = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.131", optional = true, features = ["derive"] }
smallvec = "1.6.1"

# Substrate Dependencies
## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }

## Substrate FRAME Dependencies
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }

## Substrate Pallet Dependencies
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "5bd5b842d4ea520d281b1398e1f54907c9862fcd" }

cirrus-primitives = { path = "../../primitives", default-features = false }

[features]
default = [
	"std",
]
std = [
	"codec/std",
	"serde",
	"scale-info/std",
	"log/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"cirrus-primitives/std",
]
runtime-benchmarks = [
	'hex-literal',
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking",
	"frame-system-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]
