[package]
authors = ["Serge Kovbasiuk <serge@subspace.network>"]
description = "Subspace node pallet for interacting with storage"
edition = "2018"
homepage = "https://subspace.network"
license = "Apache-2.0"
name = "pallet-feeds"
readme = "README.md"
repository = "https://github.com/subspace/subspace"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
frame-support = {version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "fa635c968e831110b13f7ff997c4cd3f5e9a3798"}
frame-system = {version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "fa635c968e831110b13f7ff997c4cd3f5e9a3798"}
log = {version = "0.4.14", default-features = false}
sp-std = {version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "fa635c968e831110b13f7ff997c4cd3f5e9a3798"}

[dev-dependencies]
serde = {version = "1.0.127"}
sp-core = {version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "fa635c968e831110b13f7ff997c4cd3f5e9a3798"}
sp-io = {version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "fa635c968e831110b13f7ff997c4cd3f5e9a3798"}
sp-runtime = {version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "fa635c968e831110b13f7ff997c4cd3f5e9a3798"}

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-std/std",
  "frame-support/std",
  "frame-system/std",
  "log/std",
]
try-runtime = ["frame-support/try-runtime"]
