[package]
name = "sp-domains"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Primitives of domains pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blake2 = { version = "0.10.6", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
hash-db = { version = "0.16.0", default-features = false }
hexlit = "0.5.5"
parity-scale-codec = { version = "3.6.5", default-features = false, features = ["derive"] }
rs_merkle = { version = "1.4.1", default-features = false }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.183", default-features = false, features = ["alloc", "derive"] }
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-application-crypto = { version = "23.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898", optional = true }
sp-consensus-slots = { version = "0.10.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-core = { version = "21.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-externalities = { version = "0.19.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-keystore = { version = "0.27.0", git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898", optional = true }
sp-runtime = { version = "24.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-runtime-interface = { version = "17.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-state-machine = { version = "0.28.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-std = { version = "8.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-trie = { version = "22.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
sp-weights = { version = "20.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "48c5ebae44b90d45863195b91e0e489eca670898" }
subspace-core-primitives = { version = "0.1.0", default-features = false, path = "../subspace-core-primitives" }
subspace-runtime-primitives = { version = "0.1.0", default-features = false, path = "../subspace-runtime-primitives" }
thiserror = { version = "1.0.48", optional = true }

[dev-dependencies]
num-traits = "0.2.16"

[features]
default = ["std"]
std = [
	"blake2/std",
	"frame-support/std",
	"hash-db/std",
	"parity-scale-codec/std",
	"rs_merkle/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-blockchain",
	"sp-application-crypto/std",
	"sp-consensus-slots/std",
	"sp-core/std",
	"sp-externalities/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-runtime-interface/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
	"sp-weights/std",
	"subspace-core-primitives/std",
	"subspace-runtime-primitives/std",
	"thiserror",
]
runtime-benchmarks = []
